// 统一错误码
export const ERROR_CODES = {
  // 通用
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  // 客户
  CUSTOMER_CREDIT_CODE_INVALID: "CUSTOMER_CREDIT_CODE_INVALID",
  // 合同
  CONTRACT_INCOMPLETE: "CONTRACT_INCOMPLETE",
  CONTRACT_NOT_COMPLETABLE: "CONTRACT_NOT_COMPLETABLE",
  CONTRACT_STATUS_INVALID: "CONTRACT_STATUS_INVALID",
  // 开票
  INVOICE_OVER_LIMIT: "INVOICE_OVER_LIMIT",
  INVOICE_INFO_INVALID: "INVOICE_INFO_INVALID",
  // 回款
  PAYMENT_DUPLICATE_REF: "PAYMENT_DUPLICATE_REF",
  PAYMENT_OVER_INVOICE: "PAYMENT_OVER_INVOICE",
  PAYMENT_OVER_CONTRACT: "PAYMENT_OVER_CONTRACT",
  // 通用
  ENTITY_IMMUTABLE: "ENTITY_IMMUTABLE",
  USER_HAS_ACTIVE_OWNERSHIP: "USER_HAS_ACTIVE_OWNERSHIP",
  CONFLICT: "CONFLICT",
  // 钉钉登录
  DINGTALK_NOT_CONFIGURED: "DINGTALK_NOT_CONFIGURED",
  DINGTALK_UPSTREAM_ERROR: "DINGTALK_UPSTREAM_ERROR",
  DINGTALK_STATE_NOT_FOUND: "DINGTALK_STATE_NOT_FOUND",
  DINGTALK_QR_EXPIRED: "DINGTALK_QR_EXPIRED",
  DINGTALK_STATE_NOT_READY: "DINGTALK_STATE_NOT_READY",
  DINGTALK_STATE_CONSUMED: "DINGTALK_STATE_CONSUMED",
  DINGTALK_PHONE_NOT_REGISTERED: "DINGTALK_PHONE_NOT_REGISTERED",
  DINGTALK_PHONE_AMBIGUOUS: "DINGTALK_PHONE_AMBIGUOUS",
  DINGTALK_USER_DISABLED: "DINGTALK_USER_DISABLED",
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  UNAUTHORIZED: "请先登录",
  FORBIDDEN: "无权限",
  NOT_FOUND: "记录不存在",
  VALIDATION_FAILED: "数据校验失败",
  INTERNAL_ERROR: "服务器内部错误",
  CUSTOMER_CREDIT_CODE_INVALID: "统一社会信用代码格式不正确",
  // (R-02/R-03/R-13/R-13b-e 已随客户状态机下线)
  CONTRACT_INCOMPLETE: "合同资料不完整（缺少附件或关键字段）",
  CONTRACT_NOT_COMPLETABLE: "合同尚不满足结清条件",
  CONTRACT_STATUS_INVALID: "合同当前状态不允许开票（须 ACTIVE）",
  INVOICE_OVER_LIMIT: "累计开票金额将超过合同总额",
  INVOICE_INFO_INVALID: "开票信息不完整或电子发票号不合规",
  PAYMENT_DUPLICATE_REF: "银行流水号重复",
  PAYMENT_OVER_INVOICE: "该发票累计回款已超出发票金额",
  PAYMENT_OVER_CONTRACT: "该合同累计回款已超出合同总额",
  ENTITY_IMMUTABLE: "终态记录不可修改/删除",
  USER_HAS_ACTIVE_OWNERSHIP: "该用户仍有进行中合同，请先转移负责人",
  CONFLICT: "档案已被他人修改,请刷新后再试",
  DINGTALK_NOT_CONFIGURED: "钉钉登录未配置,请联系管理员",
  DINGTALK_UPSTREAM_ERROR: "钉钉服务暂不可用,请稍后重试",
  DINGTALK_STATE_NOT_FOUND: "二维码已失效,请刷新重试",
  DINGTALK_QR_EXPIRED: "二维码已过期,请刷新",
  DINGTALK_STATE_NOT_READY: "请在手机上完成确认",
  DINGTALK_STATE_CONSUMED: "该二维码已被使用",
  DINGTALK_PHONE_NOT_REGISTERED: "该钉钉账号未关联系统用户,请联系管理员",
  DINGTALK_PHONE_AMBIGUOUS: "系统检测到多个匹配用户,请联系管理员",
  DINGTALK_USER_DISABLED: "账号已被禁用,请联系管理员",
};
