// 统一错误码
export const ERROR_CODES = {
  // 通用
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  // 客户
  CUSTOMER_CREDIT_CODE_INVALID: "CUSTOMER_CREDIT_CODE_INVALID",
  CUSTOMER_STATUS_INVALID: "CUSTOMER_STATUS_INVALID",
  CUSTOMER_HAS_ACTIVE_CONTRACT: "CUSTOMER_HAS_ACTIVE_CONTRACT",
  CUSTOMER_STATUS_TRANSITION_INVALID: "CUSTOMER_STATUS_TRANSITION_INVALID",
  CUSTOMER_FROZEN_ACTIVE_PAYMENT: "CUSTOMER_FROZEN_ACTIVE_PAYMENT",
  CUSTOMER_STATUS_REASON_REQUIRED: "CUSTOMER_STATUS_REASON_REQUIRED",
  // 合同
  CONTRACT_CUSTOMER_STATUS: "CONTRACT_CUSTOMER_STATUS",
  CONTRACT_INCOMPLETE: "CONTRACT_INCOMPLETE",
  CONTRACT_NOT_COMPLETABLE: "CONTRACT_NOT_COMPLETABLE",
  CONTRACT_STATUS_INVALID: "CONTRACT_STATUS_INVALID",
  // 开票
  INVOICE_OVER_LIMIT: "INVOICE_OVER_LIMIT",
  INVOICE_INFO_INVALID: "INVOICE_INFO_INVALID",
  // 回款
  PAYMENT_DUPLICATE_REF: "PAYMENT_DUPLICATE_REF",
  PAYMENT_OVER_INVOICE: "PAYMENT_OVER_INVOICE",
  PAYMENT_OVER_CONTRACT: "PAYMENT_OVER_CONTRACT",
  // 通用
  ENTITY_IMMUTABLE: "ENTITY_IMMUTABLE",
  USER_HAS_ACTIVE_OWNERSHIP: "USER_HAS_ACTIVE_OWNERSHIP",
  CONFLICT: "CONFLICT",
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  UNAUTHORIZED: "请先登录",
  FORBIDDEN: "无权限",
  NOT_FOUND: "记录不存在",
  VALIDATION_FAILED: "数据校验失败",
  INTERNAL_ERROR: "服务器内部错误",
  CUSTOMER_CREDIT_CODE_INVALID: "统一社会信用代码格式不正确",
  CUSTOMER_STATUS_INVALID: "客户状态不允许此操作（需至少一份生效中的合同）",
  CUSTOMER_HAS_ACTIVE_CONTRACT: "客户存在进行中合同或未对账回款，无法冻结",
  CUSTOMER_STATUS_TRANSITION_INVALID: "客户状态变更不被允许",
  CUSTOMER_FROZEN_ACTIVE_PAYMENT: "客户存在未对账回款，无法冻结",
  CUSTOMER_STATUS_REASON_REQUIRED: "变更到该状态需要填写原因（LOST/FROZEN 必填）",
  CONTRACT_CUSTOMER_STATUS: "客户当前状态不允许新建合同",
  CONTRACT_INCOMPLETE: "合同资料不完整（缺少附件或关键字段）",
  CONTRACT_NOT_COMPLETABLE: "合同尚不满足结清条件",
  CONTRACT_STATUS_INVALID: "合同当前状态不允许开票（须 ACTIVE）",
  INVOICE_OVER_LIMIT: "累计开票金额将超过合同总额",
  INVOICE_INFO_INVALID: "开票信息不完整或电子发票号不合规",
  PAYMENT_DUPLICATE_REF: "银行流水号重复",
  PAYMENT_OVER_INVOICE: "该发票累计回款已超出发票金额",
  PAYMENT_OVER_CONTRACT: "该合同累计回款已超出合同总额",
  ENTITY_IMMUTABLE: "终态记录不可修改/删除",
  USER_HAS_ACTIVE_OWNERSHIP: "该用户仍有进行中合同，请先转移负责人",
  CONFLICT: "档案已被他人修改,请刷新后再试",
};
